version: "3.3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_PORT: ${PGPORT}
      POSTGRES_DATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - ./dataDB:/var/lib/postgresql/data
    user: root
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - ./redis/d–∞ta:/root/services
      - ./redis/services.conf:/usr/local/etc/services/services.conf

  frontend:
    environment:
      BURL: "http://backend:${BACKEND_PORT}"
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - backend
  backend:
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRESIN: ${JWT_EXPIRESIN}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      PGHOST: postgres
      REDIS_URL: redis://redis:6379

    volumes:
      - ./back/src:/app/src
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres