version: "3.3"
services:
  frontend:
    image: ghcr.io/solutions-uray/frontend:${ENV_MODE:-latest}
    environment:
      BURL: "http://backend:${BACKEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./frontend/src:/app/src
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
  backend:
    image: ghcr.io/solutions-uray/backend:${ENV_MODE:-latest}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRESIN: ${JWT_EXPIRESIN}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      PGHOST: ${PGHOST}
      PRODUCT_URL: ${PRODUCT_URL}
      REDIS_URL: redis://redis:6379
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile