name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build a Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build
        run: docker compose build frontend
        env:
          ENV_MODE: prod
          BACKEND_PORT: ${{ secrets.PROD_BACKEND_PORT }}
          FRONTEND_PORT: ${{ secrets.PROD_FRONTEND_PORT }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to registry
        run: docker push ghcr.io/solutions-uray/frontend:prod


  deploy:
    runs-on: [ self-hosted, prod ]
    needs: [ build ]
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull frontend from registry
        run: docker pull ghcr.io/solutions-uray/frontend:prod

      - name: Start with Docker Compose
        run: docker compose up frontend -d --force-recreate
        env:
          COMPOSE_PROJECT_NAME: prod
          ENV_MODE: prod
          BACKEND_PORT: ${{ secrets.PROD_BACKEND_PORT }}
          FRONTEND_PORT: ${{ secrets.PROD_FRONTEND_PORT }}
